services:
    doppy_twig.string_extension:
        class: Doppy\TwigBundle\Twig\StringExtension
        tags:
            - { name: twig.extension }

    doppy_twig.attributes_extension:
        class: Doppy\TwigBundle\Twig\AttributesExtension
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.i18n:
        class: Twig_Extensions_Extension_I18n
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    doppy_twig.extensions.string_loader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }